### ISSUE TITLE
Pulsar Installation Error (Redhat7)

### ISSUE THREAD

**Issue by myips** [galaxyproject/pulsar#122]
Hi all,

I'm trying to implement a development version of Pulsar with Galaxy on a RHEL7 machine. I am using the latest version of Galaxy (16.10.0).

After going through the instructions for installation and changing local_env.sh , I tried run.sh and I got the following error.

```
Sourcing file ./local_env.sh
Activating virtual environment ./.venv/bin/activate
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name eggs
Failed to setup Galaxy environment properly, is GALAXY_HOME (/mnt/sdd1/galaxy) a valid Galaxy instance.
```

Can anyone shed some light on this error? I am not sure to what "name eggs" refers. Thanks in advance!

**Comment by mvdbeek** [comment]
Hi @myips, could you let us know what instructions you have been following and post the command you have launched that leads to the message you posted?
Is this while following the below quickstart instructions?
```
mkdir pulsar
cd pulsar
virtualenv venv
. venv/bin/activate # .venv\Scripts\activate if Windows
pip install pulsar-app
pulsar-config
pulsar --daemon # just pulsar if Windows
pulsar-check # runs a test job
```

**Comment by myips** [comment]
Thanks for the quick reply!

I did not follow the quick start instructions. Rather, I cloned a development version of Pulsar off of Github.

```
git clone https://github.com/galaxyproject/pulsar
cd pulsar
virtualenv .venv
. .venv/bin/activate # .venv\Scripts\activate if Windows
pip install -r requirements.txt
pip install -r dev-requirements.txt
```

As for the command that I launched, I got the same error when I did sh run.sh or pulsar --daemon.

**Comment by mvdbeek** [comment]
These are the instructions for developing pulsar, following this you can run the unit tests using `make tests`.
I would recommend first trying the quickstart instructions, and then going through https://pulsar.readthedocs.io/en/latest/install.html and then report back if this works or at what step you're having problems.

**Comment by myips** [comment]
I realize that it is the development version of pulsar. But it should work still, yes? I am using the development version because when I tried the easy installation, I noticed a couple of missing items like instructions in the app.yml file and there were instructions to uncomment out scripts from the pulsar wiki, which were not in the directory. Are those already packaged and hidden in the easyinstall version?

Running the make tests command, I received a couple of error and then it hangs and does not progress. Here is the stdout:

```
if [ -f .venv/bin/activate ]; then . .venv/bin/activate; fi; nosetests test pulsar
...................................SSS..SSS.S.Traceback (most recent call last):
  File "/mnt/sdd1/pulsar/pulsar/client/test/check.py", line 339, in __exercise_errors
    client._fetch_output(temp_output_path + "x")
  File "/mnt/sdd1/pulsar/pulsar/client/client.py", line 225, in _fetch_output
    self._populate_output_path(name, path, action_type, path_type.OUTPUT)
  File "/mnt/sdd1/pulsar/pulsar/client/client.py", line 230, in _populate_output_path
    self.__raw_download_output(name, self.job_id, path_type, output_path)
  File "/mnt/sdd1/pulsar/pulsar/client/decorators.py", line 28, in replacement
    return func(*args, **kwargs)
  File "/mnt/sdd1/pulsar/pulsar/client/client.py", line 253, in __raw_download_output
    self._raw_execute("download_output", output_params, output_path=output_path)
  File "/mnt/sdd1/pulsar/pulsar/client/client.py", line 218, in _raw_execute
    return self.job_manager_interface.execute(command, args, data, input_path, output_path)
  File "/mnt/sdd1/pulsar/pulsar/client/interface.py", line 154, in execute
    with open(result, 'rb') as result_file:
IOError: [Errno 2] No such file or directory: '/tmp/tmpVNMhyW/123456/outputs/dataset_1.datx'
.....SS.S.SSS.S.Error - <class 'webob.exc.HTTPNotFound'>: No file found with path /tmp/tmpEAgmcG/123456/outputs/dataset_1.datx.
Error - <class 'webob.exc.HTTPNotFound'>: No file found with path /tmp/tmpEAgmcG/123456/outputs/dataset_1.datx.
Error - <class 'webob.exc.HTTPNotFound'>: No file found with path /tmp/tmpEAgmcG/123456/outputs/dataset_1.datx.
Error - <class 'webob.exc.HTTPNotFound'>: No file found with path /tmp/tmpEAgmcG/123456/outputs/dataset_1.datx.
Error - <class 'webob.exc.HTTPNotFound'>: No file found with path /tmp/tmpEAgmcG/123456/outputs/dataset_1.datx.
Traceback (most recent call last):
  File "/mnt/sdd1/pulsar/pulsar/client/test/check.py", line 339, in __exercise_errors
    client._fetch_output(temp_output_path + "x")
  File "/mnt/sdd1/pulsar/pulsar/client/client.py", line 225, in _fetch_output
    self._populate_output_path(name, path, action_type, path_type.OUTPUT)
  File "/mnt/sdd1/pulsar/pulsar/client/client.py", line 230, in _populate_output_path
    self.__raw_download_output(name, self.job_id, path_type, output_path)
  File "/mnt/sdd1/pulsar/pulsar/client/decorators.py", line 28, in replacement
    return func(*args, **kwargs)
  File "/mnt/sdd1/pulsar/pulsar/client/client.py", line 253, in __raw_download_output
    self._raw_execute("download_output", output_params, output_path=output_path)
  File "/mnt/sdd1/pulsar/pulsar/client/client.py", line 218, in _raw_execute
    return self.job_manager_interface.execute(command, args, data, input_path, output_path)
  File "/mnt/sdd1/pulsar/pulsar/client/interface.py", line 106, in execute
    response = self.transport.execute(url, method=method, data=data, input_path=input_path, output_path=output_path)
  File "/mnt/sdd1/pulsar/pulsar/client/transport/standard.py", line 49, in execute
    raise PulsarClientTransportError(transport_message=exc.reason)
PulsarClientTransportError: Unknown transport error (transport message: Internal Server Error)
....SS.S.S...........SS....F

```

**Comment by mvdbeek** [comment]
> I noticed a couple of missing items like instructions in the app.yml file and there were instructions to uncomment out scripts from the pulsar wiki, which were not in the directory.

What are these missing items? I think it would be a good idea to follow along the documentation, and if there is a problem we can see if the documentation needs to be updated or if there are bugs in pulsar (which is absolutely a possibility).

**Comment by myips** [comment]
I was looking at this: https://pulsar.readthedocs.io/en/latest/job_managers.html#drmaa

The top mentioned that the app.yml file would have items to uncomment/be used for figuring out configurations. However the file I was looking at had "---" and nothing else.

I was looking under the subheading: Run-As-Real User DRMAA.

I noticed that the scripts directory was missing from the easy install version.

Perhaps I am looking at an outdated version of the instructions.

**Comment by mvdbeek** [comment]
Yes, the documentation should probably reference app.yml.sample, and I think  https://github.com/galaxyproject/pulsar/blob/master/app.yml.sample could be copied when running pulsar-config. The scripts are still there, so for example in the virtualenv you created you should have pulsar-drmaa-kill, which corresponds to https://github.com/galaxyproject/pulsar/blob/master/scripts/drmaa_kill.bash

**Comment by myips** [comment]
Great! Thanks for the clarification. I'll try it out and close the issue for now.
