### ISSUE TITLE
Stage out failures prevent the return of stdout/stderr and other useful log messages

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/pulsar#150]
If staging out fails (most often due to an expected `from_work_dir` output not existing due to a tool run failure), the entire job in Galaxy is set to failed, the error message is set to `Remote job server indicated a problem running or monitoring this job.`, and the stdout and stderr are not saved to Galaxy. As a result, it's impossible for a user to diagnose the reason for an often correctable tool run failure.

It's probably okay that it sets the job to error, but it should return `stdout` and `stderr` to Galaxy and save them, and probably set a more descriptive error message.

**Comment by jmchilton** [comment]
I think it would be best to just not fail and leave it to Galaxy to declare a job failure in this case - it isn't Pulsar's job to declare a job failed based on outputs that is Galaxy's job currently. I suspect somehow marking from work dir files as optional outputs during staging down of the job would be best. I'll take a look at this at some point this week.

**Comment by jmchilton** [comment]
It works in my hands - but this is the restful version, I'll figure out how to setup a MQ and see if that is the problem.

<img width="677" alt="screen shot 2018-02-14 at 10 43 29 am" src="https://user-images.githubusercontent.com/216771/36213367-8615b634-1174-11e8-99cd-13ac7ebf61ef.png">

**Comment by jmchilton** [comment]
I was able to recreate it, problem is definitely with MQ.

**Comment by natefoo** [comment]
This also happens if Galaxy (actually nginx in my case) returns 413 - Payload Too Large. Maybe dealing with 413 should get a new issue, but making sure it doesn't prevent the return of stdout/stderr would be good, if #159 doesn't do that (but I assume it does).
