### ISSUE TITLE
Pulsar loses jobs if restarted during job setup

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/pulsar#161]

**Comment by jmchilton** [comment]
Dup of https://github.com/galaxyproject/pulsar/issues/114?

**Comment by natefoo** [comment]
No that's a different issue (client unable to communicate with Pulsar). This issue is w/ AMQP, Pulsar doesn't save state at all when it gets a message - it acks it before the job is submitted to the DRM (which makes sense since there's staging to do) but if it's restarted during this staging period, there is no procedure to get that job set up again.

**Comment by jmchilton** [comment]
I see - so serialize the staging information to the job directory and resume staging on startup. State without a db is hard - I miss stateless Pulsar.

**Comment by natefoo** [comment]
Done. #114 isn't important (to me) at all because I don't use RESTful Pulsar.

**Comment by natefoo** [comment]
Alternatively, it might be enough to just have it refuse to shut down until it is in a safe state, but that won't allow for recovering from crashes - although a solution to that might be having Galaxy resubmit things that Pulsar seems to have lost. I wanted to do that for status updates anyway.
