### ISSUE TITLE
Error installing Pulsar

### ISSUE THREAD

**Issue by Konoyo9** [galaxyproject/pulsar#168]
Hello, 

I'm having some trouble installing Pulsar. I follow exactly the steps of the manual (both for the installation model with PyPI and the alternative model) and when running pulsar-check I get the following error:

![image](https://user-images.githubusercontent.com/44493412/47567377-aed94e00-d92e-11e8-8e2b-c947dc66f077.png)

Pulsar is running (or at least that's what it looks like when I run the command), but when I try to access port 8913 (where it is running by default as indicated by the server.ini file) I also get connection refused.

Does anyone know what's happening? I have seen in another issue that someone had a similar problem two years ago but I have not found any solution there.

Thank you very much.

**Comment by scholtalbers** [comment]
Just to comment as I encountered the same/similar issue. It may take a while for Pulsar to be operational, run without `--daemon` or check the logs and wait till you see `serving on http://127.0.0.1:8913`

**Comment by hexylena** [comment]
Potentially resolved
