### ISSUE TITLE
Freebayes bam index linking to originating server location not job inputs

### ISSUE THREAD

**Issue by Slugger70** [galaxyproject/pulsar#169]
I'm not sure if this is a Freebayes issue or if it's a deeper problem with Pulsar but I've put it here for comment.

When freebayes makes the links to the bam file and the index, for some reason when running on Pulsar the index gets linked to the originating Galaxy server metadata file location and not the inputs file directory on Pulsar

The two links in the pulsar working directory are:

```
b_0.bam -> /mnt/pulsar/files/staging/186756/inputs/dataset_290340.dat
b_0.bam.bai -> /mnt/galaxy/files/_metadata_files/021/metadata_21453.dat
```
where /mnt/galaxy is the location of Galaxy on the originating server. 

The offending code in the freebayes.xml file:
```
#for $bam_count, $input_bam in enumerate( $input_bamfiles ):
        ln -s -f '${input_bam}' 'b_${bam_count}.bam' &&
        ln -s -f '${input_bam.metadata.bam_index}' 'b_${bam_count}.bam.bai' &&
#end for
```
Both the bam file and the index file get copied by pulsar to job's inputs directory.

**Comment by jmchilton** [comment]
This is almost certainly not a Freebayes problem.
