### ISSUE TITLE
Document Remote Metadata 

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/pulsar#200]
- Set ``GALAXY_VIRTUAL_ENV`` when starting Pulsar.
- Set in Pulsar conf:
   - ``galaxy_home: /Users/john/workspace/galaxy``
   - ``galaxy_virtual_env: /Users/john/workspace/galaxy/.venv`` (probably not used)
- Set Galaxy job conf:
  -    ``<param id="remote_metadata">true</param>``
  -    ``<param id="use_metadata_binary">true</param>`` (new parameter in dev)
  -    *or*
  -    ``<param id="use_remote_datatypes">false</param>``
  -   ``<param id="remote_property_galaxy_home">/Users/john/workspace/galaxy</param>``

**Comment by natefoo** [comment]
> `galaxy_virtual_env: /Users/john/workspace/galaxy/.venv` (probably not used)

seems to match my observation that [setting it as a remote property in the job conf](https://github.com/galaxyproject/usegalaxy-playbook/blob/f2427d69caf792bd8a6092cfc8893d7fb68cbb7d/env/main/templates/galaxy/config/job_conf.xml.j2#L426) doesn't work either.

I have set `GALAXY_HOME` in my `local_env.sh` and `remote_property_galaxy_home` in my Galaxy destination config, but not `galaxy_home` in `app.yml`. So I can't tell you which of those are required.
