### ISSUE TITLE
Make a final Python 2.7 release of 0.13?

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/pulsar#233]
Changes in the master branch now (pre-0.14) fully break support for Python 2.7, but even installing 0.13 now will fail since it pulls the 20.5 versions of Galaxy libraries, which contain 2.7-breaking syntax.

Perhaps we should make one final 0.13 point release with the galaxy deps pinned to <20.5 so that it's still installable (for now) with 2.7? I know I can at least run the py27-install-wheel test with those changes, although other unpinned deps could be problematic as well (now, or some time in the future).

**Comment by gmauro** [comment]
Sounds like a good idea to me.

**Comment by natefoo** [comment]
Released as 0.13.1.
