### ISSUE TITLE
Separate tool and set_meta execution environments and stdio streams

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/pulsar#234]
A while back, Galaxy separated tool dependency stuff and tool execution into its own script, so that everything that happens for tool execution happens in its own isolated subshell, with its own stdout and stderr streams. This means that things like stdio regexes can't match messages generated by set_meta (this is a good thing), seen in (for example) galaxyproject/galaxy#10224.

Unfortunately, Pulsar does not have this capability, running everything in one big script. It'd be good to get Pulsar to behave like Galaxy here.

Part of the complication for this the way the Pulsar job script is generated. Half of the job script (everything tool related?) is generated on the Galaxy side and the other half (everything after the tool?) is generated on the Pulsar side and then they're concatenated together? It's been a couple years but that's my recollection, anyway.

I could've sworn we had an issue for this, but I couldn't find one, so apologies if this is a duplicate.

**Comment by mvdbeek** [comment]
This is mostly done in https://github.com/galaxyproject/pulsar/pull/318. I'd love for pulsar to assemble more parts of the command line, but I think we can close this now.
