### ISSUE TITLE
Glob/wildcard in from_work_dir outputs doesn't work

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/pulsar#239]
e.g. [in cutadapt](https://github.com/galaxyproject/tools-iuc/blob/41371d219eaafc811eadf7646a7f0ecf002e4239/tools/cutadapt/cutadapt.xml#L242) it attempts to collect `out1*` and `out1.fa` exists:

```
$ ls -l /jetstream/scratch0/main/jobs/1/working/out1*
-rw-rw-rw-. 1 galaxy galaxy 3390441465 Jan 11 22:46 /jetstream/scratch0/main/jobs/1/working/out1.fa
```

But collection fails:

```
Jan 11 23:01:12 jetstream-iu0.galaxyproject.org pulsar[1521]: 2021-01-11 23:01:12,696 WARNI [pulsar.managers.staging.post][[manager=jetstream_iu]-[action=postprocess]-[job=1]] Failures collecting results [Exception('Attempt to post file /jetstream/scratch0/main/jobs/1/working/out1* to URL https://galaxy/_job_files?job_id=c0ffee&job_key=deadbeef&path=/galaxy-repl/main/files/000/dataset_2.dat&file_type=output_workdir, but file does not exist.',)]
```

**Comment by jmchilton** [comment]
Well ... it shouldn't work. This is tracked somewhere in Galaxy I think, I wonder where this was last discussed.

**Comment by jmchilton** [comment]
xref https://github.com/galaxyproject/galaxy/issues/8711

**Comment by bgruening** [comment]
We have actually rewritten a few tools to not use from_work_dir if that is the error.

**Comment by bgruening** [comment]
Also this one: https://github.com/galaxyproject/tools-iuc/issues/3546

**Comment by natefoo** [comment]
@jmchilton: To get some planning out of the way before the CoFest: @Slugger70,  @cat-bro, and I would like to do some work on Pulsar, and the top of that list is doing something about this issue.

Would it be reasonable/acceptable to make Pulsar behave like Galaxy for all tools with tool profile version < XX.YY (whatever the version is that breaks globs, that afaik, doesn't exist yet - galaxyproject/galaxy#12052)?

**Comment by jmchilton** [comment]
It isn't how I would spend my time but I've dropped the ball repeatedly here clearly (a million apologies) - so I won't stand in the way if you'd like to do this. Good luck - I don't know how complicated that would be.

**Comment by natefoo** [comment]
@jmchilton are you saying that there is a better way to solve this problem? Not sure I understand your response.

**Comment by natefoo** [comment]
In testing we discovered that (with both #257 and #258) Galaxy and Pulsar still behave differently if the tool writes to the output dataset rather than the `from_work_dir` output - in this case, even though the Pulsar-side output dataset contains the output data, after the job finishes, the output is green but empty, whereas if you run it in Galaxy, it's green and contains the output data.

I haven't really looked into why this is, because ultimately this is a tool wrapper bug (it shouldn't define `from_work_dir` if it writes to the output dataset path). Galaxy and Pulsar should still probably do the same thing but I'd say the correct thing for would be to fail in both cases.

**Comment by hexylena** [comment]
:tada:
