### ISSUE TITLE
Files in __tool_directory__ not transfered

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/pulsar#249]
Hi!
Follow-up to https://github.com/galaxyproject/galaxy/issues/11573#issuecomment-793723957:

When running the jupyter interactive tools using embedded pulsar, jupyter can't find a needed file which is supposed to be [copied from  `$__tool_directory__`](https://github.com/galaxyproject/galaxy/blob/dev/tools/interactive/interactivetool_jupyter_notebook.xml#L33)

It turns out pulsar is [looking for `$__tool_directory__` paths](https://github.com/galaxyproject/pulsar/blob/master/pulsar/client/staging/up.py#L183) only in command.sh but not tool_script.sh (where the cp command is written) => the file needed by jupyter is not transferred.

And now... not sure how to fix it properly :D

**Comment by abretaud** [comment]
Hum yes I can try to write a test, it's been a while seen I've looked at galaxy tests, I'll let you know if I manage to do it (or if I fail miserably ahah)

**Comment by bgruening** [comment]
Awesome, thanks a lot @abretaud!
