### ISSUE TITLE
Update to the readthedocs configuration is needed

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/pulsar#336]
The Read the Docs build system will start requiring a configuration file v2 (.readthedocs.yaml) starting on September 25, 2023. We are sending weekly notifications about this issue to all impacted users, as well as temporary build failures (brownouts) as the date approaches for those who haven't migrated their projects. The timeline for this deprecation is as follows:

    Monday, July 24, 2023: Do the first brownout (temporarily enforce this deprecation) for 12 hours: 00:01 PST to 11:59 PST (noon)
    Monday, August 14, 2023: Do a second brownout (temporarily enforce this deprecation) for 24 hours: 00:01 PST to 23:59 PST (midnight)
    Monday, September 4, 2023: Do a third and final brownout (temporarily enforce this deprecation) for 48 hours: 00:01 PST to September 5, 2023 23:59 PST (midnight)
    Monday, September 25, 2023: Fully remove support for building documentation without configuration file v2.

More information here: https://blog.readthedocs.com/migrate-configuration-v2/

**Comment by mvdbeek** [comment]
Are you saying https://github.com/galaxyproject/pulsar/blob/master/.readthedocs.yaml is not enough ? I assume this is working.

**Comment by bgruening** [comment]
I get emails from readthedocs. This is the above text from the email.

**Comment by mvdbeek** [comment]
Can you forward me the one concerning pulsar, or is this just a mass email to everyone with an account ?

**Comment by sebastian-luna-valero** [comment]
Probably unrelated but has there been a change in https://pulsar.readthedocs.io/ today?

![image](https://github.com/galaxyproject/pulsar/assets/5345517/a426f84e-ff6c-431f-b68d-7ea1ecc3d920)

**Comment by mvdbeek** [comment]
I don't know, new layout maybe ? The thing they want from us we've already done, so not sure what this is about.
 
> Hello,
--
The build.image config key on .readthedocs.yaml has been deprecated, and will be removed on October 16, 2023.

is what's in the email, but we've got build.os since July 21st, which is what we should be using: https://github.com/galaxyproject/pulsar/blob/master/.readthedocs.yaml#L10
