### ISSUE TITLE
Pulsar control daemon

### ISSUE THREAD

**Issue by erasche** [galaxyproject/pulsar#50]
This is very much a "thinking out loud" type of feature request (so please add to it), but it would be great if there was a small daemon to sit next to pulsar which could listen to the MQ (or REST?), and handle control messages like:
- [ ] Restarting pulsar
- [ ] `git pull` + restart

Rationale:
- galaxy admin !=  cluster admin, may not have access to manage some high level details of pulsar
- cluster admin may not receive timely notice of updates to pulsar code base, if some tool could handle `git pull` and update pulsar daemons, then this would solve that issue. A central galaxy could simply send "reload" commands to all networked pulsars and have them restart. This would be hugely beneficial over the current practice of "email all your networked pulsars and ask them to update their code base + restart"

Concerns:
- Losing some of the separation of privileges that are a great thing about Pulsar, namely that the Galaxy admin has zero control over how pulsar behaves on the remote end.
- It might be tough to gracefully reload the pulsar-control deamon if we add new actions to the above list over time (though if they're using supervisord, simply killing ourselves with an exit code should be enough to trigger restarting)
- _MUST_ not be able to affect any changes to Pulsar's configuration or there could be problems (e.g someone gains access to queue and tells pulsar-control to point to fully compromised MQ server)

**Comment by jmchilton** [comment]
Also relevant - https://github.com/galaxyproject/gravity.

Thought @natefoo is calling the executable ``galaxy`` now - so I guess I have to build a whole new one for pulsar. :wink:

**Comment by erasche** [comment]
Sorry, vaven't been able to work on pulsar a lot lately (HPC folks have
their heads so far up their asses the university project isn't worth my
volunteer time), I'll try and get this done for GCC since it, along with
installing tool dependencies, are some of the major features that are
needed for getting up and running with a cloud.

Would be nice to roll a 'pulsar init' command into galaxy as part of the
scope of this. I can envision a lot more bidirectional communication with
galaxy over MQ happening and being useful here...

ons. 25. feb. 2015, 02.59 skrev John Chilton <notifications@github.com>:

**Comment by erasche** [comment]
It finally dawned on me what you meant--`gravity` has `supervisord` built in for managing processes, which is what you meant here. GOT IT. Sigh...my brain, somedays.

**Comment by erasche** [comment]
These are all awful ideas and I don't know what I was thinking. Closing :)
