### ISSUE TITLE
Discarding Jobs at Startup

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/pulsar#58]
Review discarding jobs at startup and make sure Pulsar sends messages back to Galaxy indicating that jobs are being discarded if it cannot verify that postprocessing has completed.

**Comment by jmchilton** [comment]
Closed sort of with 61ed774ae6c67e7f0d891999def7233d1572013c.

**Comment by natefoo** [comment]
"sort of"?

**Comment by jmchilton** [comment]
well... it is better than it was... #66 will help too.
