### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/pulsar#60]
Pulsar needs a logo.

**Comment by afgane** [comment]
Here's an idea:
![pulsarlogo_idea](https://cloud.githubusercontent.com/assets/338642/6858027/a41b0efa-d3e1-11e4-9d71-b43a903656f6.jpg)

**Comment by erasche** [comment]
Throw some ideas in as well.

![pulsar](https://cloud.githubusercontent.com/assets/458683/6858643/ac620f44-d3de-11e4-976a-2694f1ba36dc.png)

**Comment by STruong1** [comment]
Hello,

I saw that you needed a logo and thought I might submit one. Hope you like it!
![pulsar_retro](https://cloud.githubusercontent.com/assets/10429580/7193550/06bd58f8-e457-11e4-85c9-532f44395bc7.png)

**Comment by carlfeberhard** [comment]
![pulsar](https://cloud.githubusercontent.com/assets/5102959/7205321/81adb96e-e4f6-11e4-81e5-d7c362ceeda7.png)

**Comment by petrkadlec** [comment]
I would keep it clean and simple with galaxy project branding. Vertical bars might be easier to associate with the name - pulses.
![pulsar](https://cloud.githubusercontent.com/assets/12165223/7445429/dc87c5a0-f1b2-11e4-9e9e-c73aabf7f04d.png)

**Comment by afgane** [comment]
+1 @petrkadlec

**Comment by jmchilton** [comment]
Thanks for the contributions @afgane @erasche @carlfeberhard and @STruong1 - they are all great. The team has decided that there should be common elements with the main Galaxy logo so I think it will be best to go with @petrkadlec logo here - which is also great!

**Comment by martenson** [comment]
I wonder what cool story will @blankenberg find for this one :)

**Comment by blankenberg** [comment]
@martenson with the vertical bars looking like an EQ animation, the first thing that comes to mind "Pulsar, it really whips the llama's ass", but probably should come up with something else.

**Comment by jxtx** [comment]
I like the vertical bars a lot. Specifically because it is a *modification*
of the Galaxy logo -- less of a literal reuse than the proposed E in
planemo. So +1

On Monday, May 4, 2015, John Chilton <notifications@github.com> wrote:

> Thanks for the contributions @afgane <https://github.com/afgane> @erasche
> <https://github.com/erasche> @carlfeberhard
> <https://github.com/carlfeberhard> and @STruong1
> <https://github.com/STruong1> - they are all great. The team has decided
> that there should be common elements with the main Galaxy logo so I think
> it will be best to go with @petrkadlec <https://github.com/petrkadlec>
> logo here - which is also great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/pulsar/issues/60#issuecomment-98753910>.
>


-- 
jt (mobile)
