### ISSUE TITLE
When configured to use 'copy' file_action pulsar still attempts http transfer

### ISSUE THREAD

**Issue by dctrud** [galaxyproject/pulsar#63]
Hi John - I emailed about this earlier, but did some more digging. I'm guessing my hacks on the code in the diffs below break things in other setups, but they are letting the 'copy' file_action complete.

Tried to configure pulsar with a destination as follows:

```xml
<destination id="pulsar_rest_dest" runner="pulsar_rest">
            <param id="url">http://localhost:3032/</param>
            <param id="private_token">xxxxxx</param>
            <param id="default_file_action">copy</param>
            <param id="submit_user">$__user_name__</param>
            <param id="submit_native_specification">--partition=super</param>
            <param id="file_action_config">/project/apps/galaxy/galaxy/config/pulsar_actions.yaml</param>
        </destination>
```
Job submission always failed. Found pulsar was trying to upload files via http, not copy them. Worked through call trace and found that action_type is being picked up correctly, but is not being passed into the client.put_file method. This method has a default action_type in it's def which means http transfer was always used.

Modified to pass the action_type through with diff:

```diff
--- a/lib/pulsar/client/staging/up.py
+++ b/lib/pulsar/client/staging/up.py
@@ -348,8 +348,7 @@ class TransferTracker(object):
         if action.staging_needed:
             local_action = action.staging_action_local
             if local_action:
-                response = self.client.put_file(path, type, name=name, contents=contents)
-
+                response = self.client.put_file(path, type, name=name, contents=contents, action_type=action.action_type)
                 def get_path():
                     return response['path']
             else:

```
It then attempted to copy files, but was failing in the shutil copy call as the path obtained from pulsar is a json structure, not a bare string path. abspath calls mangling it into a combination of the GALAXY_HOME and the json structure:

```
==> handler1.log <==
galaxy.jobs.runners.pulsar ERROR 2015-04-08 15:46:17,100 failure running job 83
Traceback (most recent call last):
  File "/project/apps/galaxy/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 209, in queue_job
    job_id = pulsar_submit_job(client, client_job_description, remote_job_config)
  File "/project/apps/galaxy/galaxy/lib/pulsar/client/staging/up.py", line 22, in submit_job
    file_stager = FileStager(client, client_job_description, job_config)
  File "/project/apps/galaxy/galaxy/lib/pulsar/client/staging/up.py", line 91, in __init__
    self.__upload_input_files()
  File "/project/apps/galaxy/galaxy/lib/pulsar/client/staging/up.py", line 160, in __upload_input_files
    self.__upload_input_file(input_file)
  File "/project/apps/galaxy/galaxy/lib/pulsar/client/staging/up.py", line 166, in __upload_input_file
    self.transfer_tracker.handle_transfer(input_file, path_type.INPUT)
  File "/project/apps/galaxy/galaxy/lib/pulsar/client/staging/up.py", line 351, in handle_transfer
    response = self.client.put_file(path, type, name=name, contents=contents, action_type=action.action_type)
  File "/project/apps/galaxy/galaxy/lib/pulsar/client/client.py", line 177, in put_file
    copy(path, pulsar_path)
  File "/project/apps/galaxy/galaxy/lib/pulsar/client/util.py", line 27, in copy
    shutil.copyfile(source, destination)
  File "/project/apps/galaxy/.pyenv/versions/2.7.8/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/project/apps/galaxy/galaxy/{"path": "/project/apps/galaxy/pulsar/files/staging/d283a74499144b89ae73666463c2bc73/inputs/dataset_91.dat"}'
```

Tried to fix this with a naive patch:

```diff
--- a/lib/pulsar/client/client.py
+++ b/lib/pulsar/client/client.py
@@ -1,5 +1,5 @@
 import os
-from json import dumps
+from json import dumps, loads

 from .destination import submit_params
 from .setup_handler import build as build_setup_handler
@@ -173,7 +173,7 @@ class JobClient(BaseJobClient):
         if action_type == 'transfer':
             return self._upload_file(args, contents, input_path)
         elif action_type == 'copy':
-            pulsar_path = self._raw_execute('path', args)
+            pulsar_path = loads(self._raw_execute('path', args))['path']
             copy(path, pulsar_path)
             return {'path': pulsar_path}

```

It's now staging files by copying. I'm not sure how much other stuff these diffs are likely to break though.

**Comment by dctrud** [comment]
Just a note that with these nasty hacks I'm now successfully running jobs on our SLURM cluster as real users. Everything is NFS mounted across the galaxy server and our SLURM cluster, but pulsar used to stage potentially private user data so that permissions can stay locked down via umask.

* 'copy' file_action is being used to stage anything from galaxy/database/files, which is potentially private, and umask will ensure not world read in the staging dir.
* 'none' file_action used for all standard gnome data etc. which we keep somewhere else.
* object_store_umask set to 0007

This is awesome @jmchilton - so flexible. Definitely appreciate the massive amount of work you've obviously done on this!

**Comment by jmchilton** [comment]
Very sorry about the bug - but I am excited it is working for you now. Many thanks for the detailed bug report and fix!

After I release Pulsar 0.3.0 - I am going to commit an embedded Pulsar job runner into Galaxy (https://trello.com/c/4YwVZBtq). So that you can do what you are doing (staging and interfacing with the DRM using Pulsar) without actually having to setup and run a pulsar server, presumably it will be a little more robust also without needing to communicate between processes.

**Comment by jmchilton** [comment]
Also - I assume you are running against the ``dev`` branch of Galaxy for the auth stuff anyway so I am just going to patch ``dev``. If it would be useful to patch the latest release though - just say the word and I will open a PR for that.

**Comment by dctrud** [comment]
John  - no need to apologize, I'm very thankful that the functionality exists. The embedded pulsar sounds great. I look forward to that.

I am running against dev for the auth stuff at the moment - no need to patch the release for me.

Thanks again!
