### ISSUE TITLE
uwsgi invalid request block size

### ISSUE THREAD

**Issue by dtrudg** [galaxyproject/pulsar#64]
When using the default uwsgi settings in server.ini (with and nginx front-end) i see the following error in the log which is causing some requests to pulsar from galaxy handler fail:

```
invalid request block size: 9614 (max 4096)...skip
```

Set `buffer-size=32768` in the `[uwsgi]` section of `server.ini` to side-step this problem. It appears as though it might be down to large request headers being sent:

http://lists.unbit.it/pipermail/uwsgi/2012-October/004878.html

Not sure whether this is something that needs investigation / resolution?

**Comment by erasche** [comment]
I've seen the same error pop in galaxy when talking to toolsheds. There really isn't much resolution other than updating uWSGI options. Might be worth documenting.

**Comment by mvdbeek** [comment]
At one point that was added to the galaxy uwsgi docs, but we're also not supporting uwsgi anymore.
