### ISSUE TITLE
Allow permission restrictions on staging/<jobid> directory?

### ISSUE THREAD

**Issue by dctrud** [galaxyproject/pulsar#65]
I'm using pulsar to get around the limitation of Galaxy DRMAA as a real user, where the Galaxy datasets need to be world-readable. This is not acceptable for our user base. I have the following solution in use.... 

* Galaxy files dir is 660 galaxy:galaxy - so that galaxy itself can see everything, but no user on the cluster can access anyone else's dataset.

* Pulsar is being used to submit external real-user DRMAA jobs, where the 'copy' file action is used so that the private galaxy files/* are staged and available to the job. Anything not private, such as genome indices is using the 'none' action as is world-readable.

* Galaxy/pulsar can always access what they need, as relevant files have group ownership 'galaxy'. 

* The pulsar chown functionality gives neccessary real-user rights when jobs run under SLURM on the cluster.

* Am running galaxy and pulsar under umask 0007 so that dataset files aren't created world-readable. This ensures they aren't world readable when copied into the pulsar job staging dir.

This seems to be working nicely. However, instead of relying on umask it would be nice if it was possible to restrict the permissions on the `staging/<jobid>` directories, which always seem to be completely open (drwxrwxrwx).

I looked around, but couldn't find any configuration option, or obvious place where the perms are set for these job staging dirs.

Would it be possible to allow these dirs to be created (drwxrwx---) so that access can be restricted without relying on the umask when the staged datasets were originally created by galaxy?

Would be happy to work on this for a PR if I can get a pointer r.e. where the open perms on the staging dirs are set - I've looked but I'm lost.

**Comment by jmchilton** [comment]
Added an explicit option - this is a good idea. It also worked on my local machine to run ``umask 007`` prior launching pulsar - that might be the better way to accomplish this so that all directories pulsar creates are secured - and not just the ones explicitly related to jobs.

**Comment by dctrud** [comment]
Thanks John.... agreed that umask works, doing that at the moment. I just like the idea of there being an explicit option, so that the privacy of those files isn't broken if e.g. pulsar wasn't started with umask first. This is great, thanks again!

**Comment by natefoo** [comment]
Just wanted to say it's awesome you've got pulsar working this way, to work around the limitations in Galaxy's internal real user handling.

Is your underlying filesystem capable of extended ACLs? It might be reasonable for real-user job handling to just modify ACLs to avoid expensive copying. But this does mean potentially maintaining a bunch of fs-specific plugins.

**Comment by dctrud** [comment]
@natefoo - We could use ACLs on the fs that the galaxy data is currently on, but really want to avoid that for now as there's a storage upgrade in planning which may use an fs lacking full ACL support. I like that idea though - think I might try that if we end up with ACL support.

Copying the data isn't prohibitively expensive for us at the moment. Lucky enough to have ~500MB/s throughput, and many TB of space available.

**Comment by natefoo** [comment]
4 Gbit/s over NFS? Sorcery!

**Comment by dctrud** [comment]
Looks more like 300MB/sec this morning.... Still pretty good though considering Galaxy is an ESXi VM, and is sharing the virtual network (which uses an FDR infiniband card) with other things.

I think the ACL route will sound nicer if usage really takes off here for very large datasets.
